### ISSUE TITLE
URL rewriting?

### ISSUE THREAD

**Issue by carsongross** [stfnhrrs/HookTuber#2]
Hey,

Saw this plugin and tried it out, but it didn't work on the sites I was looking at.

I found this other plugin:

  https://github.com/josh2112/url-rewriter

that does URL rewriting.  I wonder if something like that but that was tailored just for pewtube would be a good solution...

Thanks for your work on this!

**Comment by stfnhrrs** [comment]
hey @carsongross, this plugin isn't supposed to rewrite the urls, it allows you to browse youtube.com and switches just the video player to hooktube.

**Comment by carsongross** [comment]
Ah, sorry for the misunderstanding

**Comment by stfnhrrs** [comment]
No worries!
